name: Security Scans

on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
  schedule:
    - cron: "0 3 * * 1"  # каждый понедельник в 03:00 UTC

permissions:
  contents: read

env:
  PYTHON_VERSION: "3.11"

jobs:
  secret-scan:
    name: Secret Scan (trufflehog)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0  # полная история для сканирования всех коммитов

      - name: Run trufflehog
        uses: trufflesecurity/trufflehog@v3.82.13
        with:
          extra_args: --only-verified

  code-security:
    name: Code Security (bandit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-security-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-security-

      - name: Install bandit
        run: pip install bandit

      - name: Run bandit
        run: bandit -r src/ -f json -o bandit-report.json || true

      - name: Check bandit results
        run: |
          bandit -r src/ --severity-level high --confidence-level high
          echo "Bandit scan passed: no HIGH severity issues found."

  dependency-scan:
    name: Dependency Scan (pip-audit)
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: ${{ env.PYTHON_VERSION }}

      - name: Cache pip dependencies
        uses: actions/cache@v4
        with:
          path: ~/.cache/pip
          key: pip-audit-${{ hashFiles('requirements.txt') }}
          restore-keys: |
            pip-audit-

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install pip-audit
          if [ -f requirements.txt ]; then pip install -r requirements.txt; fi

      - name: Run pip-audit
        run: pip-audit --strict --desc

  notify:
    name: Notify on Security Failure
    needs: [secret-scan, code-security, dependency-scan]
    if: failure()
    runs-on: ubuntu-latest
    steps:
      - name: Send Slack notification
        uses: slackapi/slack-github-action@v2.0.0
        with:
          webhook: ${{ secrets.SLACK_WEBHOOK_URL }}
          webhook-type: incoming-webhook
          payload: |
            {
              "text": "Security Scan Failed on ${{ github.repository }}",
              "blocks": [
                {
                  "type": "section",
                  "text": {
                    "type": "mrkdwn",
                    "text": "*Security Scan Failed*\n*Repository:* ${{ github.repository }}\n*Branch:* ${{ github.ref_name }}\n*Commit:* ${{ github.sha }}\n*Author:* ${{ github.actor }}\n*Action required:* review security findings immediately.\n*Details:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|View logs>"
                  }
                }
              ]
            }
